# Generated by Django 2.1.7 on 2019-05-11 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
